config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end
  
  resources :charges, only: [:new, :create]

  get 'welcome/index'

  get 'welcome/about'

  get 'downgrade' => 'charges#downgrade'

  root 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :users
  belongs_to :wikis
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :wikis
    has_many :collaborators
    has_many :collaborated_wikis, through: :collaborators, source: :wiki
    enum role: [:standard, :premium, :admin]
    
    after_initialize :check_role
    
    def check_role
       self.role ||= :standard           
     end
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
  
  scope :visible_to, -> (user) { user && (user.admin? || user.premium?) ? all : where(private: false) }

  
  def collaborator?(user)
    collaborators.where(user_id: user.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit
    before_action :authenticate_user!
    protect_from_forgery with: :exception

    private

    def require_sign_in
        unless current_user
            flash[:alert] = 'You must be logged in to do that'
            redirect_to new_session_path
        end
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    def new
        if current_user.premium?
            flash[:message] = 'You are already a premium user.'
            redirect_to root_path
        end
    end

    def create
        @amount = 1_500

        customer = Stripe::Customer.create(
            email: params[:stripeEmail],
            source: params[:stripeToken]
        )

        charge = Stripe::Charge.create(
            customer: customer.id,
            amount: 1_500,
            description: 'Premium Account',
            currency: 'usd'
        )
        current_user.premium!

        flash[:notice] = "Thanks for all the money, #{current_user.email}! Your account has been upgraded to premium."
        redirect_to edit_user_registration_path

    rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to new_charge_path
    end

    def downgrade
        @amount = -1_500

        current_user.standard!

        flash[:notice] = 'Your account been downgraded to standard.'
        redirect_to edit_user_registration_path

    rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to download_path
    end

    private

    def charges_params
        params.require(:charges).permit(:stripeToken, :amount)
    end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
    def update
        @wiki.collaborator = params[:wiki][:collaborator]
    end

    def create
        @wiki = Wiki.find(params[:wiki_id])
        @collaborator = @wiki.collaborators.build(user_id: params[:user_id])

        if @collaborator.save
            flash[:notice] = 'Collaborator was added successfully.'
            redirect_to edit_wiki_path(@wiki)
        else
            flash[:alert] = 'Collaborator was not added.  Please try again.'
            redirect_to edit_wiki_path(@wiki)
        end
    end

    def destroy
        @collaborator = Collaborator.find_by_user_id_and_wiki_id(params[:user_id], params[:wiki_id])

        if @collaborator.destroy
            flash[:notice] = 'Collaborator was removed successfully.'
            redirect_to edit_wiki_path(params[:wiki_id])
        else
            flash[:alert] = 'Collaborator was not removed.  Please try again.'
            redirect_to edit_wiki_path(params[:wiki_id])
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
    
    def about
    end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
    before_action :authenticate_user!

    def index
        @wikis = policy_scope(Wiki)
     end

    def show
        @wiki = Wiki.find(params[:id])
    end

    def new
        @wiki = Wiki.new
    end

    def create
        @wiki = Wiki.new
        @wiki.title = params[:wiki][:title]
        @wiki.body = params[:wiki][:body]
        @wiki.private = params[:wiki][:private]
        @wiki.user = current_user

        if @wiki.save

            flash[:notice] = 'Wiki was saved.'
            redirect_to @wiki
        else

            flash.now[:alert] = 'There was an error saving the Wiki. Please try again.'
            render :new
      end
    end

    def edit
        @wiki = Wiki.find(params[:id])
    end

    def update
        @wiki = Wiki.find(params[:id])
        @wiki.title = params[:wiki][:title]
        @wiki.body = params[:wiki][:body]
        @wiki.private = params[:wiki][:private]
        @wiki.user_id = current_user.id
        @wiki.collaborator = params[:wiki][:collaborator]

        if @wiki.save
            flash[:notice] = 'Wiki was updated.'
            redirect_to @wiki
        else
            flash.now[:alert] = 'There was an error saving the wiki. Please try again.'
            render :edit
        end
    end

    def destroy
        @wiki = Wiki.find(params[:id])

        if @wiki.destroy
            flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
            redirect_to wikis_path
        else
            flash.now[:alert] = 'There was an error deleting the wiki.'
            render :show
        end
    end

    private

    def user_not_authorized
        flash[:error] = 'You are not authorized to perform this action.'
        redirect_to(request.referrer || root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:  true,
      hard_wrap:    true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:     true,
      superscript:  true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper

  def stripe_btn_data(amount=1500)
    {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Premium Membership - #{current_user.email}",
      amount: amount
    }
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
    def user_is_authorized_for_post?(post)
        current_user && (current_user == wiki.user || current_user.admin?)
   end
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $15.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A premium account"
          data-amount="1500"></script>
<% end %> 

app/views/collaborators/_form.html.erb
<h3>Add Collaborators to
    <%= @wiki.title %>
    Wiki (showing all users)</h3>
<table>
    <tr>
        <th>Email</th>
        <th>Give Access</th>
    </tr>
    <% @user = User.all %>
    <% @user.each do |user| %>
    <tr>
        <td>
            <%= user.email %>
        </td>
        <td>
            <% if @wiki.collaborator? (user) %>
            <%= link_to "Remove as collaborator", wiki_collaborator_path(wiki_id: @wiki.id, user_id: user.id), method: :delete, data: {:confirm => 'Are you sure?'}, class: 'btn btn-danger' %>
        <% else %>
            <%= link_to "Add as collaborator", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: 'btn btn-success' %>
            <% end %>
        </td>
    </tr>
    <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Blocipedia</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <div class="container">
            <ul class="nav nav-tabs">
                <li><%= link_to "Blocipedia", welcome_index_path %></li>
                <li><%= link_to "About", welcome_about_path %></li>
                <li><%= link_to "Wikis", wikis_path %></li>
                <% if current_user %>
                <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
            <% else %>
                <li><%= link_to('Login', new_user_session_path)  %></li>
                <li><%= link_to('Register now!', new_user_registration_path)  %></li>
                <% end %>
            </ul>
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
            <%= yield %>
        </div>
    </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
<%= link_to "Log in", new_session_path(resource_name) %><br/>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
<%= link_to "Sign up", new_registration_path(resource_name) %><br/>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
<%= link_to "Forgot your password?", new_password_path(resource_name) %><br/>
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
<%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br/>
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
<%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br/>
<% end -%>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

 <div class="row">
   <div class="col-md-6">
     <p><%= @user.role %></p>
   </div>
   <div class="col-md-6">
     <% if @user.standard? %>
     <%= render "charges/new"  %>
     <% elsif @user.premium? %>
     <%= render "registrations/edit"  %>
     <% end %>
   </div>
 </div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
 <% if user_signed_in? %>
   Logged in as <strong><%= current_user.email %></strong>.
   <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
   <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
 <% else %>
   <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
   <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
 <% end %>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
<div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
</div>
<div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
</div>
<% if (current_user.premium? || current_user.admin?) && (@wiki.id == nil || @wiki.user == current_user)%>
<div class="form-group">
    <%= f.label :private, class: 'checkbox' %>
    <%= f.check_box :private %>
    Private wiki
</div>
<% end %>
<div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
</div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for wikis</p>
        <ul>
            <li>Wikipedia articles should be written in a professional manner.</li>
            <li>Make your articles clear.</li>
            <li>State facts that may be obvious to you, but are not necessarily obvious to the reader.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= render partial: 'form' %>
    </div>
</div>

<% if @wiki.private? && ( user_id = current_user.id || current_user.admin? ) %>
<div class="col-md-8">
    <%= render partial: 'collaborators/form' %>
</div>
<% end %>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>

<% @wikis.each do |wiki| %>
<div class="media">
    <div class="media-body">
        <h4 class="media-heading">
            <%= link_to wiki.title, wiki %>
        </h4>
    </div>
</div>
<% end %>
<div class="col-md-4">
    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for wikis</p>
        <ul>
            <li>Good articles start with a brief lead section introducing the topic.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= form_for @wiki do |f| %>
        <div class="form-group">

            <%= f.label :title %>

            <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
        </div>
        <div class="form-group">
            <%= f.label :body %>
            <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
        </div>
        <div class="form-group">
            <%= f.label :private %>
            <%= select("wiki", "private", [['True', true], ['False', false]], {}, { :class => 'form-control' })  %>
        </div>
        <div class="form-group">

            <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
        <% end %>
    </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>
<h5>Owned by
    <%= @wiki.user.email %></h5>
<h6>
    Collaborators:
    <% array = [] %>
    <% User.all.map do |user| %>
    <% if @wiki.collaborator?(user) %>
    <% array << user.email %>
    <% end %>
    <% end %>
    <% if array == nil %>
    <%= "none" %>
<% else %>
    <%= array.join(", ") %>
    <% end %>
</h6>

<div class="row">
    <div class="col-md-8">
        <p><%= markdown(@wiki.body) %></p>
    </div>
    <div class="col-md-4">
        <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
        <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
    </div>
</div>